/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.ui.contentassist;

import com.laegler.stubbr.lang.ui.contentassist.AbstractStubbrLangProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class StubbrLangProposalProvider extends AbstractStubbrLangProposalProvider {
}
