/**
 * PMBOK Language
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.serializer;

import com.laegler.stubbr.lang.serializer.StubbrLangSyntacticSequencer;

@SuppressWarnings("all")
public class StubbrSyntacticSequencer extends StubbrLangSyntacticSequencer {
}
