/**
 * PMBOK Language
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.serializer;

import com.laegler.stubbr.lang.serializer.StubbrLangSemanticSequencer;

@SuppressWarnings("all")
public class StubbrSemanticSequencer extends StubbrLangSemanticSequencer {
}
