/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chapter Project Management</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterProjectManagement#getProjects <em>Projects</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterProjectManagement#getScm <em>Scm</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterProjectManagement#getIssueManagement <em>Issue Management</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterProjectManagement#getDistroManagement <em>Distro Management</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterProjectManagement#getCi <em>Ci</em>}</li>
 * </ul>
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterProjectManagement()
 * @model
 * @generated
 */
public interface ChapterProjectManagement extends Chapter
{
  /**
   * Returns the value of the '<em><b>Projects</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.DevProject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Projects</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projects</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterProjectManagement_Projects()
   * @model containment="true"
   * @generated
   */
  EList<DevProject> getProjects();

  /**
   * Returns the value of the '<em><b>Scm</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Level1Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scm</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scm</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterProjectManagement_Scm()
   * @model containment="true"
   * @generated
   */
  EList<Level1Attribute> getScm();

  /**
   * Returns the value of the '<em><b>Issue Management</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Level1Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Issue Management</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Issue Management</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterProjectManagement_IssueManagement()
   * @model containment="true"
   * @generated
   */
  EList<Level1Attribute> getIssueManagement();

  /**
   * Returns the value of the '<em><b>Distro Management</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Level1Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Distro Management</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distro Management</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterProjectManagement_DistroManagement()
   * @model containment="true"
   * @generated
   */
  EList<Level1Attribute> getDistroManagement();

  /**
   * Returns the value of the '<em><b>Ci</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Level1Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ci</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ci</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterProjectManagement_Ci()
   * @model containment="true"
   * @generated
   */
  EList<Level1Attribute> getCi();

} // ChapterProjectManagement
