/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chapter Presentation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterPresentation#getUiFramework <em>Ui Framework</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterPresentation#getLayouts <em>Layouts</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterPresentation#getStylings <em>Stylings</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterPresentation#getViews <em>Views</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterPresentation#getTransitions <em>Transitions</em>}</li>
 * </ul>
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPresentation()
 * @model
 * @generated
 */
public interface ChapterPresentation extends Chapter
{
  /**
   * Returns the value of the '<em><b>Ui Framework</b></em>' attribute.
   * The literals are from the enumeration {@link com.laegler.stubbr.lang.stubbrLang.UiFramework}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ui Framework</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ui Framework</em>' attribute.
   * @see com.laegler.stubbr.lang.stubbrLang.UiFramework
   * @see #setUiFramework(UiFramework)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPresentation_UiFramework()
   * @model
   * @generated
   */
  UiFramework getUiFramework();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.ChapterPresentation#getUiFramework <em>Ui Framework</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ui Framework</em>' attribute.
   * @see com.laegler.stubbr.lang.stubbrLang.UiFramework
   * @see #getUiFramework()
   * @generated
   */
  void setUiFramework(UiFramework value);

  /**
   * Returns the value of the '<em><b>Layouts</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Layout}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Layouts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layouts</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPresentation_Layouts()
   * @model containment="true"
   * @generated
   */
  EList<Layout> getLayouts();

  /**
   * Returns the value of the '<em><b>Stylings</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Styling}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stylings</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stylings</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPresentation_Stylings()
   * @model containment="true"
   * @generated
   */
  EList<Styling> getStylings();

  /**
   * Returns the value of the '<em><b>Views</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.View}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Views</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Views</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPresentation_Views()
   * @model containment="true"
   * @generated
   */
  EList<View> getViews();

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Transition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Transitions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPresentation_Transitions()
   * @model containment="true"
   * @generated
   */
  EList<Transition> getTransitions();

} // ChapterPresentation
