/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chapter Persistence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterPersistence#getDatabases <em>Databases</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterPersistence#getDatasources <em>Datasources</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterPersistence#getPersistenceUnits <em>Persistence Units</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterPersistence#getEntities <em>Entities</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterPersistence#getEnumerations <em>Enumerations</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterPersistence#getRelationships <em>Relationships</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterPersistence#isCustomIds <em>Custom Ids</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterPersistence#getJavaType <em>Java Type</em>}</li>
 * </ul>
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPersistence()
 * @model
 * @generated
 */
public interface ChapterPersistence extends Chapter
{
  /**
   * Returns the value of the '<em><b>Databases</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Database}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Databases</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Databases</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPersistence_Databases()
   * @model containment="true"
   * @generated
   */
  EList<Database> getDatabases();

  /**
   * Returns the value of the '<em><b>Datasources</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Level1Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Datasources</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Datasources</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPersistence_Datasources()
   * @model containment="true"
   * @generated
   */
  EList<Level1Attribute> getDatasources();

  /**
   * Returns the value of the '<em><b>Persistence Units</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Level1Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Persistence Units</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Persistence Units</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPersistence_PersistenceUnits()
   * @model containment="true"
   * @generated
   */
  EList<Level1Attribute> getPersistenceUnits();

  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Entity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entities</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPersistence_Entities()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntities();

  /**
   * Returns the value of the '<em><b>Enumerations</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Enumeration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Enumerations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumerations</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPersistence_Enumerations()
   * @model containment="true"
   * @generated
   */
  EList<Enumeration> getEnumerations();

  /**
   * Returns the value of the '<em><b>Relationships</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Relationship}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relationships</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relationships</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPersistence_Relationships()
   * @model containment="true"
   * @generated
   */
  EList<Relationship> getRelationships();

  /**
   * Returns the value of the '<em><b>Custom Ids</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Custom Ids</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Ids</em>' attribute.
   * @see #setCustomIds(boolean)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPersistence_CustomIds()
   * @model
   * @generated
   */
  boolean isCustomIds();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.ChapterPersistence#isCustomIds <em>Custom Ids</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom Ids</em>' attribute.
   * @see #isCustomIds()
   * @generated
   */
  void setCustomIds(boolean value);

  /**
   * Returns the value of the '<em><b>Java Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Java Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Java Type</em>' containment reference.
   * @see #setJavaType(JvmTypeReference)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterPersistence_JavaType()
   * @model containment="true"
   * @generated
   */
  JvmTypeReference getJavaType();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.ChapterPersistence#getJavaType <em>Java Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Java Type</em>' containment reference.
   * @see #getJavaType()
   * @generated
   */
  void setJavaType(JvmTypeReference value);

} // ChapterPersistence
