/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chapter Environment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterEnvironment#getInfrastructure <em>Infrastructure</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterEnvironment#getTestMethods <em>Test Methods</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.ChapterEnvironment#getRuntime <em>Runtime</em>}</li>
 * </ul>
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterEnvironment()
 * @model
 * @generated
 */
public interface ChapterEnvironment extends Chapter
{
  /**
   * Returns the value of the '<em><b>Infrastructure</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Level1Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Infrastructure</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Infrastructure</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterEnvironment_Infrastructure()
   * @model containment="true"
   * @generated
   */
  EList<Level1Attribute> getInfrastructure();

  /**
   * Returns the value of the '<em><b>Test Methods</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Level1Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Test Methods</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test Methods</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterEnvironment_TestMethods()
   * @model containment="true"
   * @generated
   */
  EList<Level1Attribute> getTestMethods();

  /**
   * Returns the value of the '<em><b>Runtime</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Runtime</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Runtime</em>' containment reference.
   * @see #setRuntime(com.laegler.stubbr.lang.stubbrLang.Runtime)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getChapterEnvironment_Runtime()
   * @model containment="true"
   * @generated
   */
  com.laegler.stubbr.lang.stubbrLang.Runtime getRuntime();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.ChapterEnvironment#getRuntime <em>Runtime</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Runtime</em>' containment reference.
   * @see #getRuntime()
   * @generated
   */
  void setRuntime(com.laegler.stubbr.lang.stubbrLang.Runtime value);

} // ChapterEnvironment
