/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Dev Project Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getDevProjectType()
 * @model
 * @generated
 */
public enum DevProjectType implements Enumerator
{
  /**
   * The '<em><b>PARENT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PARENT_VALUE
   * @generated
   * @ordered
   */
  PARENT(0, "PARENT", "parent"),

  /**
   * The '<em><b>DOCS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DOCS_VALUE
   * @generated
   * @ordered
   */
  DOCS(1, "DOCS", "documentation"),

  /**
   * The '<em><b>ANNOTATIONS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ANNOTATIONS_VALUE
   * @generated
   * @ordered
   */
  ANNOTATIONS(2, "ANNOTATIONS", "annotations"),

  /**
   * The '<em><b>COMMONS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COMMONS_VALUE
   * @generated
   * @ordered
   */
  COMMONS(3, "COMMONS", "commons"),

  /**
   * The '<em><b>DATA MODEL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DATA_MODEL_VALUE
   * @generated
   * @ordered
   */
  DATA_MODEL(4, "DATA_MODEL", "dataModel"),

  /**
   * The '<em><b>PERSISTENCE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PERSISTENCE_VALUE
   * @generated
   * @ordered
   */
  PERSISTENCE(5, "PERSISTENCE", "persistence"),

  /**
   * The '<em><b>BUSINESS MODEL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BUSINESS_MODEL_VALUE
   * @generated
   * @ordered
   */
  BUSINESS_MODEL(6, "BUSINESS_MODEL", "businessModel"),

  /**
   * The '<em><b>BUSINESS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BUSINESS_VALUE
   * @generated
   * @ordered
   */
  BUSINESS(7, "BUSINESS", "business"),

  /**
   * The '<em><b>PROCESS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PROCESS_VALUE
   * @generated
   * @ordered
   */
  PROCESS(8, "PROCESS", "process"),

  /**
   * The '<em><b>MATLAB</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MATLAB_VALUE
   * @generated
   * @ordered
   */
  MATLAB(9, "MATLAB", "matlab"),

  /**
   * The '<em><b>WEB</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WEB_VALUE
   * @generated
   * @ordered
   */
  WEB(10, "WEB", "webProject"),

  /**
   * The '<em><b>REST GENERATE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REST_GENERATE_VALUE
   * @generated
   * @ordered
   */
  REST_GENERATE(11, "REST_GENERATE", "restGenerator"),

  /**
   * The '<em><b>REST SERVICE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REST_SERVICE_VALUE
   * @generated
   * @ordered
   */
  REST_SERVICE(12, "REST_SERVICE", "restService"),

  /**
   * The '<em><b>REST CLIENT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REST_CLIENT_VALUE
   * @generated
   * @ordered
   */
  REST_CLIENT(13, "REST_CLIENT", "restClient"),

  /**
   * The '<em><b>SOAP SERVICE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SOAP_SERVICE_VALUE
   * @generated
   * @ordered
   */
  SOAP_SERVICE(14, "SOAP_SERVICE", "soapService"),

  /**
   * The '<em><b>SOAP CLIENT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SOAP_CLIENT_VALUE
   * @generated
   * @ordered
   */
  SOAP_CLIENT(15, "SOAP__CLIENT", "soapClient"),

  /**
   * The '<em><b>EAR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EAR_VALUE
   * @generated
   * @ordered
   */
  EAR(16, "EAR", "ear"),

  /**
   * The '<em><b>DOCKER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DOCKER_VALUE
   * @generated
   * @ordered
   */
  DOCKER(17, "DOCKER", "docker");

  /**
   * The '<em><b>PARENT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PARENT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PARENT
   * @model literal="parent"
   * @generated
   * @ordered
   */
  public static final int PARENT_VALUE = 0;

  /**
   * The '<em><b>DOCS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DOCS</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DOCS
   * @model literal="documentation"
   * @generated
   * @ordered
   */
  public static final int DOCS_VALUE = 1;

  /**
   * The '<em><b>ANNOTATIONS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ANNOTATIONS</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ANNOTATIONS
   * @model literal="annotations"
   * @generated
   * @ordered
   */
  public static final int ANNOTATIONS_VALUE = 2;

  /**
   * The '<em><b>COMMONS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>COMMONS</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #COMMONS
   * @model literal="commons"
   * @generated
   * @ordered
   */
  public static final int COMMONS_VALUE = 3;

  /**
   * The '<em><b>DATA MODEL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DATA MODEL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DATA_MODEL
   * @model literal="dataModel"
   * @generated
   * @ordered
   */
  public static final int DATA_MODEL_VALUE = 4;

  /**
   * The '<em><b>PERSISTENCE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PERSISTENCE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PERSISTENCE
   * @model literal="persistence"
   * @generated
   * @ordered
   */
  public static final int PERSISTENCE_VALUE = 5;

  /**
   * The '<em><b>BUSINESS MODEL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>BUSINESS MODEL</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #BUSINESS_MODEL
   * @model literal="businessModel"
   * @generated
   * @ordered
   */
  public static final int BUSINESS_MODEL_VALUE = 6;

  /**
   * The '<em><b>BUSINESS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>BUSINESS</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #BUSINESS
   * @model literal="business"
   * @generated
   * @ordered
   */
  public static final int BUSINESS_VALUE = 7;

  /**
   * The '<em><b>PROCESS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>PROCESS</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PROCESS
   * @model literal="process"
   * @generated
   * @ordered
   */
  public static final int PROCESS_VALUE = 8;

  /**
   * The '<em><b>MATLAB</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>MATLAB</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MATLAB
   * @model literal="matlab"
   * @generated
   * @ordered
   */
  public static final int MATLAB_VALUE = 9;

  /**
   * The '<em><b>WEB</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WEB</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WEB
   * @model literal="webProject"
   * @generated
   * @ordered
   */
  public static final int WEB_VALUE = 10;

  /**
   * The '<em><b>REST GENERATE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>REST GENERATE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #REST_GENERATE
   * @model literal="restGenerator"
   * @generated
   * @ordered
   */
  public static final int REST_GENERATE_VALUE = 11;

  /**
   * The '<em><b>REST SERVICE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>REST SERVICE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #REST_SERVICE
   * @model literal="restService"
   * @generated
   * @ordered
   */
  public static final int REST_SERVICE_VALUE = 12;

  /**
   * The '<em><b>REST CLIENT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>REST CLIENT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #REST_CLIENT
   * @model literal="restClient"
   * @generated
   * @ordered
   */
  public static final int REST_CLIENT_VALUE = 13;

  /**
   * The '<em><b>SOAP SERVICE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SOAP SERVICE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SOAP_SERVICE
   * @model literal="soapService"
   * @generated
   * @ordered
   */
  public static final int SOAP_SERVICE_VALUE = 14;

  /**
   * The '<em><b>SOAP CLIENT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SOAP CLIENT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SOAP_CLIENT
   * @model name="SOAP__CLIENT" literal="soapClient"
   * @generated
   * @ordered
   */
  public static final int SOAP_CLIENT_VALUE = 15;

  /**
   * The '<em><b>EAR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EAR</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EAR
   * @model literal="ear"
   * @generated
   * @ordered
   */
  public static final int EAR_VALUE = 16;

  /**
   * The '<em><b>DOCKER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DOCKER</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DOCKER
   * @model literal="docker"
   * @generated
   * @ordered
   */
  public static final int DOCKER_VALUE = 17;

  /**
   * An array of all the '<em><b>Dev Project Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final DevProjectType[] VALUES_ARRAY =
    new DevProjectType[]
    {
      PARENT,
      DOCS,
      ANNOTATIONS,
      COMMONS,
      DATA_MODEL,
      PERSISTENCE,
      BUSINESS_MODEL,
      BUSINESS,
      PROCESS,
      MATLAB,
      WEB,
      REST_GENERATE,
      REST_SERVICE,
      REST_CLIENT,
      SOAP_SERVICE,
      SOAP_CLIENT,
      EAR,
      DOCKER,
    };

  /**
   * A public read-only list of all the '<em><b>Dev Project Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<DevProjectType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Dev Project Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DevProjectType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      DevProjectType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Dev Project Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DevProjectType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      DevProjectType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Dev Project Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DevProjectType get(int value)
  {
    switch (value)
    {
      case PARENT_VALUE: return PARENT;
      case DOCS_VALUE: return DOCS;
      case ANNOTATIONS_VALUE: return ANNOTATIONS;
      case COMMONS_VALUE: return COMMONS;
      case DATA_MODEL_VALUE: return DATA_MODEL;
      case PERSISTENCE_VALUE: return PERSISTENCE;
      case BUSINESS_MODEL_VALUE: return BUSINESS_MODEL;
      case BUSINESS_VALUE: return BUSINESS;
      case PROCESS_VALUE: return PROCESS;
      case MATLAB_VALUE: return MATLAB;
      case WEB_VALUE: return WEB;
      case REST_GENERATE_VALUE: return REST_GENERATE;
      case REST_SERVICE_VALUE: return REST_SERVICE;
      case REST_CLIENT_VALUE: return REST_CLIENT;
      case SOAP_SERVICE_VALUE: return SOAP_SERVICE;
      case SOAP_CLIENT_VALUE: return SOAP_CLIENT;
      case EAR_VALUE: return EAR;
      case DOCKER_VALUE: return DOCKER;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private DevProjectType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //DevProjectType
