/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Di Bounds</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.DiBounds#getX <em>X</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.DiBounds#getY <em>Y</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.DiBounds#getWidth <em>Width</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.DiBounds#getHeight <em>Height</em>}</li>
 * </ul>
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getDiBounds()
 * @model
 * @generated
 */
public interface DiBounds extends DiDiagramElement
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>X</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getDiBounds_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.DiBounds#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Y</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getDiBounds_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.DiBounds#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

  /**
   * Returns the value of the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Width</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Width</em>' attribute.
   * @see #setWidth(int)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getDiBounds_Width()
   * @model
   * @generated
   */
  int getWidth();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.DiBounds#getWidth <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Width</em>' attribute.
   * @see #getWidth()
   * @generated
   */
  void setWidth(int value);

  /**
   * Returns the value of the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Height</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Height</em>' attribute.
   * @see #setHeight(int)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getDiBounds_Height()
   * @model
   * @generated
   */
  int getHeight();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.DiBounds#getHeight <em>Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Height</em>' attribute.
   * @see #getHeight()
   * @generated
   */
  void setHeight(int value);

} // DiBounds
