/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Di Plane</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.DiPlane#getName <em>Name</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.DiPlane#getBpmnElement <em>Bpmn Element</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.DiPlane#getPlaneElements <em>Plane Elements</em>}</li>
 * </ul>
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getDiPlane()
 * @model
 * @generated
 */
public interface DiPlane extends DiDiagramElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getDiPlane_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.DiPlane#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Bpmn Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bpmn Element</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bpmn Element</em>' reference.
   * @see #setBpmnElement(BusinessProcess)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getDiPlane_BpmnElement()
   * @model
   * @generated
   */
  BusinessProcess getBpmnElement();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.DiPlane#getBpmnElement <em>Bpmn Element</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bpmn Element</em>' reference.
   * @see #getBpmnElement()
   * @generated
   */
  void setBpmnElement(BusinessProcess value);

  /**
   * Returns the value of the '<em><b>Plane Elements</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.DiPlaneElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Plane Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plane Elements</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getDiPlane_PlaneElements()
   * @model containment="true"
   * @generated
   */
  EList<DiPlaneElement> getPlaneElements();

} // DiPlane
