/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gateway Diverging</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.GatewayDiverging#getOptions <em>Options</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.GatewayDiverging#getGatewayConverging <em>Gateway Converging</em>}</li>
 * </ul>
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getGatewayDiverging()
 * @model
 * @generated
 */
public interface GatewayDiverging extends Gateway, OptionFlowNode
{
  /**
   * Returns the value of the '<em><b>Options</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.stubbr.lang.stubbrLang.Option}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Options</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' containment reference list.
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getGatewayDiverging_Options()
   * @model containment="true"
   * @generated
   */
  EList<Option> getOptions();

  /**
   * Returns the value of the '<em><b>Gateway Converging</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gateway Converging</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gateway Converging</em>' containment reference.
   * @see #setGatewayConverging(GatewayConverging)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getGatewayDiverging_GatewayConverging()
   * @model containment="true"
   * @generated
   */
  GatewayConverging getGatewayConverging();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.GatewayDiverging#getGatewayConverging <em>Gateway Converging</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gateway Converging</em>' containment reference.
   * @see #getGatewayConverging()
   * @generated
   */
  void setGatewayConverging(GatewayConverging value);

} // GatewayDiverging
