/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Given Step</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getGivenStep()
 * @model
 * @generated
 */
public interface GivenStep extends Step
{
} // GivenStep
