/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Option Flow Node</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getOptionFlowNode()
 * @model
 * @generated
 */
public interface OptionFlowNode extends EObject
{
} // OptionFlowNode
