/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Output Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.OutputText#getValue <em>Value</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.OutputText#getStyle <em>Style</em>}</li>
 * </ul>
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getOutputText()
 * @model
 * @generated
 */
public interface OutputText extends Element
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getOutputText_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.OutputText#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Style</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Style</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Style</em>' reference.
   * @see #setStyle(Styling)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getOutputText_Style()
   * @model
   * @generated
   */
  Styling getStyle();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.OutputText#getStyle <em>Style</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Style</em>' reference.
   * @see #getStyle()
   * @generated
   */
  void setStyle(Styling value);

} // OutputText
