/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Person</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getPerson()
 * @model
 * @generated
 */
public interface Person extends Stakeholder
{
} // Person
