/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Role</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getRole()
 * @model
 * @generated
 */
public interface Role extends Stakeholder
{
} // Role
