/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Styling</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.Styling#getName <em>Name</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.Styling#getLabel <em>Label</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.Styling#getDocumentation <em>Documentation</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.Styling#getBaseColor <em>Base Color</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.Styling#getHighLightColor <em>High Light Color</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.Styling#getTextColor <em>Text Color</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.Styling#getFontSize <em>Font Size</em>}</li>
 * </ul>
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getStyling()
 * @model
 * @generated
 */
public interface Styling extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getStyling_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.Styling#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Label</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getStyling_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.Styling#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

  /**
   * Returns the value of the '<em><b>Documentation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Documentation</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Documentation</em>' attribute.
   * @see #setDocumentation(String)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getStyling_Documentation()
   * @model
   * @generated
   */
  String getDocumentation();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.Styling#getDocumentation <em>Documentation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Documentation</em>' attribute.
   * @see #getDocumentation()
   * @generated
   */
  void setDocumentation(String value);

  /**
   * Returns the value of the '<em><b>Base Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Base Color</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base Color</em>' attribute.
   * @see #setBaseColor(String)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getStyling_BaseColor()
   * @model
   * @generated
   */
  String getBaseColor();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.Styling#getBaseColor <em>Base Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base Color</em>' attribute.
   * @see #getBaseColor()
   * @generated
   */
  void setBaseColor(String value);

  /**
   * Returns the value of the '<em><b>High Light Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>High Light Color</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>High Light Color</em>' attribute.
   * @see #setHighLightColor(String)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getStyling_HighLightColor()
   * @model
   * @generated
   */
  String getHighLightColor();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.Styling#getHighLightColor <em>High Light Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>High Light Color</em>' attribute.
   * @see #getHighLightColor()
   * @generated
   */
  void setHighLightColor(String value);

  /**
   * Returns the value of the '<em><b>Text Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Text Color</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text Color</em>' attribute.
   * @see #setTextColor(String)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getStyling_TextColor()
   * @model
   * @generated
   */
  String getTextColor();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.Styling#getTextColor <em>Text Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text Color</em>' attribute.
   * @see #getTextColor()
   * @generated
   */
  void setTextColor(String value);

  /**
   * Returns the value of the '<em><b>Font Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Font Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Font Size</em>' attribute.
   * @see #setFontSize(String)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getStyling_FontSize()
   * @model
   * @generated
   */
  String getFontSize();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.Styling#getFontSize <em>Font Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Font Size</em>' attribute.
   * @see #getFontSize()
   * @generated
   */
  void setFontSize(String value);

} // Styling
