/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.Task#getTaskType <em>Task Type</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.Task#getDialog <em>Dialog</em>}</li>
 * </ul>
 *
 * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getTask()
 * @model
 * @generated
 */
public interface Task extends Activity, InteractionNode
{
  /**
   * Returns the value of the '<em><b>Task Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.laegler.stubbr.lang.stubbrLang.TaskType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Task Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Task Type</em>' attribute.
   * @see com.laegler.stubbr.lang.stubbrLang.TaskType
   * @see #setTaskType(TaskType)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getTask_TaskType()
   * @model
   * @generated
   */
  TaskType getTaskType();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.Task#getTaskType <em>Task Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Task Type</em>' attribute.
   * @see com.laegler.stubbr.lang.stubbrLang.TaskType
   * @see #getTaskType()
   * @generated
   */
  void setTaskType(TaskType value);

  /**
   * Returns the value of the '<em><b>Dialog</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dialog</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dialog</em>' reference.
   * @see #setDialog(View)
   * @see com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage#getTask_Dialog()
   * @model
   * @generated
   */
  View getDialog();

  /**
   * Sets the value of the '{@link com.laegler.stubbr.lang.stubbrLang.Task#getDialog <em>Dialog</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dialog</em>' reference.
   * @see #getDialog()
   * @generated
   */
  void setDialog(View value);

} // Task
