/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.web;

import java.util.concurrent.ExecutorService;

/**
 * Initialization support for running Xtext languages in web applications.
 */
/* @FinalFieldsConstructor */@SuppressWarnings("all")
public class StubbrLangWebSetup /* implements StubbrLangStandaloneSetup  */{
  private final /* Provider<ExecutorService> */Object executorServiceProvider;
  
  @Override
  public /* Injector */Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nStubbrLangRuntimeModule cannot be resolved."
      + "\nThe method or field Guice is undefined"
      + "\nThe method or field Modules is undefined"
      + "\nInvalid number of arguments. The constructor StubbrLangWebModule() is not applicable for the arguments (Provider)"
      + "\nThe field StubbrLangWebSetup.executorServiceProvider refers to the missing type Provider"
      + "\ncreateInjector cannot be resolved"
      + "\noverride cannot be resolved"
      + "\nwith cannot be resolved");
  }
}
