/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.Provider;
import com.google.inject.util.Modules;
import com.laegler.stubbr.lang.StubbrLangRuntimeModule;
import com.laegler.stubbr.lang.StubbrLangStandaloneSetup;
import com.laegler.stubbr.lang.web.StubbrLangWebModule;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class StubbrLangWebSetup extends StubbrLangStandaloneSetup {
  private final Provider<ExecutorService> executorServiceProvider;
  
  @Override
  public Injector createInjector() {
    final StubbrLangRuntimeModule runtimeModule = new StubbrLangRuntimeModule();
    final StubbrLangWebModule webModule = new StubbrLangWebModule(this.executorServiceProvider);
    Modules.OverriddenModuleBuilder _override = Modules.override(runtimeModule);
    Module _with = _override.with(webModule);
    return Guice.createInjector(_with);
  }
  
  public StubbrLangWebSetup(final Provider<ExecutorService> executorServiceProvider) {
    super();
    this.executorServiceProvider = executorServiceProvider;
  }
}
