/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.validation;

import com.laegler.stubbr.lang.validation.AbstractStubbrLangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class StubbrLangValidator extends AbstractStubbrLangValidator {
}
