/*
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.ui.tests;

import com.google.inject.Injector;
import com.laegler.stubbr.lang.ui.internal.LangActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class StubbrLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LangActivator.getInstance().getInjector("com.laegler.stubbr.lang.StubbrLang");
	}

}
