/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang.impl;

import com.laegler.stubbr.lang.stubbrLang.ChapterProjectStructure;
import com.laegler.stubbr.lang.stubbrLang.Level1Attribute;
import com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Chapter Project Structure</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.impl.ChapterProjectStructureImpl#isIsNestedParent <em>Is Nested Parent</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.impl.ChapterProjectStructureImpl#getTestMethods <em>Test Methods</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ChapterProjectStructureImpl extends ChapterImpl implements ChapterProjectStructure
{
  /**
   * The default value of the '{@link #isIsNestedParent() <em>Is Nested Parent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsNestedParent()
   * @generated
   * @ordered
   */
  protected static final boolean IS_NESTED_PARENT_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsNestedParent() <em>Is Nested Parent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsNestedParent()
   * @generated
   * @ordered
   */
  protected boolean isNestedParent = IS_NESTED_PARENT_EDEFAULT;

  /**
   * The cached value of the '{@link #getTestMethods() <em>Test Methods</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTestMethods()
   * @generated
   * @ordered
   */
  protected EList<Level1Attribute> testMethods;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ChapterProjectStructureImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StubbrLangPackage.eINSTANCE.getChapterProjectStructure();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isIsNestedParent()
  {
    return isNestedParent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIsNestedParent(boolean newIsNestedParent)
  {
    boolean oldIsNestedParent = isNestedParent;
    isNestedParent = newIsNestedParent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, StubbrLangPackage.CHAPTER_PROJECT_STRUCTURE__IS_NESTED_PARENT, oldIsNestedParent, isNestedParent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Level1Attribute> getTestMethods()
  {
    if (testMethods == null)
    {
      testMethods = new EObjectContainmentEList<Level1Attribute>(Level1Attribute.class, this, StubbrLangPackage.CHAPTER_PROJECT_STRUCTURE__TEST_METHODS);
    }
    return testMethods;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case StubbrLangPackage.CHAPTER_PROJECT_STRUCTURE__TEST_METHODS:
        return ((InternalEList<?>)getTestMethods()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case StubbrLangPackage.CHAPTER_PROJECT_STRUCTURE__IS_NESTED_PARENT:
        return isIsNestedParent();
      case StubbrLangPackage.CHAPTER_PROJECT_STRUCTURE__TEST_METHODS:
        return getTestMethods();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case StubbrLangPackage.CHAPTER_PROJECT_STRUCTURE__IS_NESTED_PARENT:
        setIsNestedParent((Boolean)newValue);
        return;
      case StubbrLangPackage.CHAPTER_PROJECT_STRUCTURE__TEST_METHODS:
        getTestMethods().clear();
        getTestMethods().addAll((Collection<? extends Level1Attribute>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case StubbrLangPackage.CHAPTER_PROJECT_STRUCTURE__IS_NESTED_PARENT:
        setIsNestedParent(IS_NESTED_PARENT_EDEFAULT);
        return;
      case StubbrLangPackage.CHAPTER_PROJECT_STRUCTURE__TEST_METHODS:
        getTestMethods().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case StubbrLangPackage.CHAPTER_PROJECT_STRUCTURE__IS_NESTED_PARENT:
        return isNestedParent != IS_NESTED_PARENT_EDEFAULT;
      case StubbrLangPackage.CHAPTER_PROJECT_STRUCTURE__TEST_METHODS:
        return testMethods != null && !testMethods.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (isNestedParent: ");
    result.append(isNestedParent);
    result.append(')');
    return result.toString();
  }

} //ChapterProjectStructureImpl
