/**
 * generated by Xtext 2.10.0
 */
package com.laegler.stubbr.lang.stubbrLang.impl;

import com.laegler.stubbr.lang.stubbrLang.StubbrLangPackage;
import com.laegler.stubbr.lang.stubbrLang.Task;
import com.laegler.stubbr.lang.stubbrLang.TaskType;
import com.laegler.stubbr.lang.stubbrLang.View;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Task</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.impl.TaskImpl#getTaskType <em>Task Type</em>}</li>
 *   <li>{@link com.laegler.stubbr.lang.stubbrLang.impl.TaskImpl#getDialog <em>Dialog</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TaskImpl extends ActivityImpl implements Task
{
  /**
   * The default value of the '{@link #getTaskType() <em>Task Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaskType()
   * @generated
   * @ordered
   */
  protected static final TaskType TASK_TYPE_EDEFAULT = TaskType.BLANK;

  /**
   * The cached value of the '{@link #getTaskType() <em>Task Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaskType()
   * @generated
   * @ordered
   */
  protected TaskType taskType = TASK_TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getDialog() <em>Dialog</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDialog()
   * @generated
   * @ordered
   */
  protected View dialog;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TaskImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StubbrLangPackage.eINSTANCE.getTask();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TaskType getTaskType()
  {
    return taskType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTaskType(TaskType newTaskType)
  {
    TaskType oldTaskType = taskType;
    taskType = newTaskType == null ? TASK_TYPE_EDEFAULT : newTaskType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, StubbrLangPackage.TASK__TASK_TYPE, oldTaskType, taskType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public View getDialog()
  {
    if (dialog != null && dialog.eIsProxy())
    {
      InternalEObject oldDialog = (InternalEObject)dialog;
      dialog = (View)eResolveProxy(oldDialog);
      if (dialog != oldDialog)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, StubbrLangPackage.TASK__DIALOG, oldDialog, dialog));
      }
    }
    return dialog;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public View basicGetDialog()
  {
    return dialog;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDialog(View newDialog)
  {
    View oldDialog = dialog;
    dialog = newDialog;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, StubbrLangPackage.TASK__DIALOG, oldDialog, dialog));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case StubbrLangPackage.TASK__TASK_TYPE:
        return getTaskType();
      case StubbrLangPackage.TASK__DIALOG:
        if (resolve) return getDialog();
        return basicGetDialog();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case StubbrLangPackage.TASK__TASK_TYPE:
        setTaskType((TaskType)newValue);
        return;
      case StubbrLangPackage.TASK__DIALOG:
        setDialog((View)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case StubbrLangPackage.TASK__TASK_TYPE:
        setTaskType(TASK_TYPE_EDEFAULT);
        return;
      case StubbrLangPackage.TASK__DIALOG:
        setDialog((View)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case StubbrLangPackage.TASK__TASK_TYPE:
        return taskType != TASK_TYPE_EDEFAULT;
      case StubbrLangPackage.TASK__DIALOG:
        return dialog != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (taskType: ");
    result.append(taskType);
    result.append(')');
    return result.toString();
  }

} //TaskImpl
